### ISSUE TITLE
Figure out the earliest point in teaching at which we can introduce some testing

### ISSUE THREAD

**Issue by gvwilson** [rangle/angular-training-slides#224]
We currently introduce testing fairly late in the teaching sequence. What are the earliest points at which we could plausibly introduce some of Angular 2's testing infrastructure without confusing students by using dark magic they won't yet understand?

**Comment by rpdasilva** [comment]
@gvwilson It seems to me, if exercises are based around the use of Angular CLI, and we have students create a new project when we introduce CLI, then we can get away with introducing testing right around slide 76 (Currently "Testing" in the CLI section) assuming of course we're okay with introducing karma/jasmine at this time as well.

Since the CLI generates spec files whenever you generate a project/component/service etc. as long as a student has some existing knowledge of what a module/component/service looks like, testing can probably be introduced in parallel.

Specifically by slide 76, students should have already generated a new project, and we've already gone through what a basic component looks like, what a module is and it's various configurations.
There's no reason we couldn't go into the default tests the CLI provides for the generated `app.component.ts`.

```
TestBed.configureTestingModule({
      declarations: [
        AppComponent
      ],
    }).compileComponents();
```

^ this directly relates to the modules content. This is just creating a module wrapped in TestBed. Aside from karma/jasmine, there's no black magic here, it's all just "test" related content. No other Angular dependent knowledge is really needed here. 

Other tests in the file look like...

```
it('should create the app', async(() => {
    const fixture = TestBed.createComponent(AppComponent);
    const app = fixture.debugElement.componentInstance;
    expect(app).toBeTruthy();
  }));
```

They're simple and would help lay the foundation for more complicated setups, test, and mocking later on.

The idea being, as soon as we introduce a new concept, we can show how to test that concept. As the course continues on, testing can slowly be expanded upon. When services or other modules get introduced, we can introduce mocking those out in the module. It would certainly make the testing portion of the course more incremental - every exercise can potentially be paired with testing as well

**Comment by gvwilson** [comment]
We are going to stick to the current structure of having testing as its own module - too distracting to interleave testing with other topics.
