### ISSUE TITLE
Should we introduce Yarn for package management?

### ISSUE THREAD

**Issue by gvwilson** [rangle/angular-training-slides#301]

**Comment by gvwilson** [comment]
If so, we should describe installation on slide 10

**Comment by mdegani** [comment]
My arguments for using yarn in our training:
1. Many Angular projects use it, including those in the Angular github organization
2. Commands are simpler: `yarn serve-dev` vs `npm run serve-dev`.  `yarn` instead of `npm install`.
3. It's faster
4. It's low risk. You don't lose anything by using Yarn, you can revert to npm at any time.

Argument against:
1. It's another thing to install on each person's machine. I would argue that it is worth installing though.
2. It's something extra to explain, though if they're new to the javascript world, it saves us from having to explain npm

**Comment by gvwilson** [comment]
We will show people how to use Yarn everywhere we show them how to use NPM, and add install instructions for Yarn for those who want it.
