### ISSUE TITLE
Figure out how best to host slide decks on GitHub Pages

### ISSUE THREAD

**Issue by gvwilson** [rangle/angular-training-slides#340]
We would like to be able to host and view decks on GitHub Pages without too much hackery, but webpack makes it...interesting. cc @BrendanFDMoore

**Comment by winkerVSbecks** [comment]
@gvwilson would you like this to be an automated process – for every commit it will auto-deploy? Or a manual process – `npm run deploy`?

**Comment by BrendanFDMoore** [comment]
Personally I like the manual deploy structure better, sits it reflects how I manually rebase my gh-pages branch currently and force push it only when ready for an update.

But that would be easy to switch on and off via commit hook I assume.

**Comment by winkerVSbecks** [comment]
So, since we have a webpack setup we have to deploy the build directory to `gh-pages`. I generally use this script to do that [X1011/git-directory-deploy](https://raw.githubusercontent.com/X1011/git-directory-deploy/master/deploy.sh). It uses git to checkout `gh-pages` branch, commit contents of `dist` to it and then push it. Works quite well.

**Comment by BrendanFDMoore** [comment]
Awesome - thanks @winkerVSbecks !
