### ISSUE TITLE
/services-quiz-2: update choices since both 2 and 3 are correct

### ISSUE THREAD

**Issue by gvwilson** [rangle/angular-training-slides#353]

**Comment by mdegani** [comment]
Based on crude experimentation, an injected dependency is not created until the class that injects it is instantiated. There doesn't seem to be a lot of documentation on this, but if you provide a service and inject it into a component that is not initially visible because it is on another route and then navigate so that it becomes visible its constructor is not called until after after you navigate and Angular actually needs it (even when everything is all in one module).  In other words DI is lazy.

It appears as though DI instantiates dependencies only when they're needed (assuming we're providing it as a singleton and not factory).

We don't really cover this in the slides though.

How about this:

a (wrong): Dependency injection give your classes references to global variables. :trollface: (this can probably be improved, but let's diagnose whether they missed the point entirely). 
b (correct): By default, a new instance of an injected service is constructed only if it has not been injected before, otherwise an existing instance is reused.
c (wrong): If you specify that you want a service injected, Angular automatically registers its provider in the root module of the app.

**Comment by gvwilson** [comment]
1. Do we need a couple of slides to explain when classes are instantiated during DI, or is that going down the rabbit hole?
2. I like the MCQ - please go ahead and add it.

**Comment by mdegani** [comment]
@gvwilson no, I don't think explaining it adds much value.
