### ISSUE TITLE
Rework general testing content

### ISSUE THREAD

**Issue by jamesbs** [rangle/angular-training-slides#363]
Slide order or general approach to presenting testing is a bit confusing, the testing content should be reworked.
- introduces a lot of complexity very quickly, hard to digest for new users of angular

**Comment by mdegani** [comment]
@gvwilson I have been working on the [services branch of the todo app](https://github.com/gvwilson/angular-todo-example/tree/services) as the starting point for the testing sides and have made some changes:
1. Removed the BehaviourSubject from the service and am now using the array directly.
2. I'm passing down the items from AppComponent to the to-do-list component through the input.

**Comment by mdegani** [comment]
As I've been working on the testing slides, I've been thinking it would be simpler to dive directly into testing rather than worrying about dealing with the technical debt of failing tests. A simple solutions (and good trick for devs to know) is to use `fdescribe` which let's you temporarily not worry about failing tests.

**Comment by gvwilson** [comment]
Closed by large PR reworking testing slides.
