### ISSUE TITLE
Modify reveal.js so that URLs and slide numbers on pages match

### ISSUE THREAD

**Issue by gvwilson** [rangle/angular-training-slides#446]
URLs are zero-based, slide numbers are 1-based - reconcile.

**Comment by mdegani** [comment]
Here is where the url is changed:
https://github.com/hakimel/reveal.js/blob/9f8e4d5742df486cce577f6e0dbae666aabc4eb1/js/reveal.js#L3482

**Comment by rpdasilva** [comment]
Well that's annoying - without hacking around that, we'd have to generate or add ID's to every `<section>` tag, which means reordering those will get fun

**Comment by mdegani** [comment]
I thought the purpose of story was simply to make the numbers match.  So simply want to tbe `url = '/' + id + 1;`

**Comment by rpdasilva** [comment]
If we're forking the library, sure - was hoping we wouldn't need to do that

**Comment by rpdasilva** [comment]
Because we're using generated markdown we'd have to do something like this for every slide...
`<!-- .slide: id="23" -->`
(If we're sticking with whatever current API is available to us

In other words, whichever "solution" we come up with to generate UUID's for each slide could also be applied here

Or more specifically, if we solve the issue of generating an ordered numerical id here, we can extend that solution for our unique id generation later

**Comment by mdegani** [comment]
We will not be doing this. Please see #413.
